---
language: node_js
node_js:
  - "9"
services:
  - mongodb
  - postgresql
env:
  - PGUSER=postgres PGDATABASE=machinomy_test
before_script:
  - psql -c 'create database machinomy_test;' -U postgres -d postgres
  - yarn migrate
script:
  - yarn lint
  - yarn build
  - yarn test
